name = input('What is your name? ')
favourite_colour = input('What is your favourite_colour? ')
age = input('What is your age? ')
school = input('What is your school name? ')
college = input('What is your college name? ')
job = input('What is your company name? ')
position = input('What is your position? ')
print('|' + name + ' like ' + favourite_colour + ' | ')
print( age )
print('|' + ' name of school ' + school + ' || ' + ' name of college ' + college + ' | ')
print('| ' + ' name of your company ' + job + ' || ' + ' What is your position ' + position + ' | ')